### ISSUE TITLE
Explore: "Open In Maps" Consistency

### ISSUE THREAD

**Issue by justinhuskey** [infinitered/ChainReactApp2023#115]
Could we change this buttons on the "Explore" screen to be the style from the "Venue" screen?
<img width="349" alt="Screenshot 2023-04-12 at 5 21 58 PM" src="https://user-images.githubusercontent.com/4877999/231614107-bab0c490-fac8-4842-aa2e-f56d55f512b6.png">
<img width="238" alt="Screenshot 2023-04-12 at 5 22 17 PM" src="https://user-images.githubusercontent.com/4877999/231614108-88320db6-40d2-4d2c-9d29-72309b76bb99.png">

**Comment by mazenchami** [comment]
@justinhuskey this is totally doable. i just noticed the code is displaying both in some cases. the one you have marked with the "green check" is for the website and the one with the "red x" is the link to open in maps. I assume we want the style of the "green check" that opens in maps. I'll go down that route, please correct me or let me know if we still want the website to also open.

**Comment by justinhuskey** [comment]
That's correct @mazenchami! We can just get rid of the big purple button with the red x.
