### ISSUE TITLE
Infinispin - not sure

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#131]
Did a pull to refresh and it doesn't seem to want to time out.

https://user-images.githubusercontent.com/997157/232861314-dcd80101-48e7-41c7-a651-c14c1c81c433.MP4

**Comment by ecroce** [comment]
Came here to report this same bug. The pull down doesn't have to be forceful either, it's just a casual scroll to the bottom and then back up shows the infinity load.
