### ISSUE TITLE
Don't Localize time - just at PT if needed

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#135]
People will download the app, and look at it in different places around the world.  It can be confusing.

For instance, this makes it look like workshops end at 7pm!

![image](https://user-images.githubusercontent.com/997157/232864162-dc8a59b6-b74f-4d3e-ad9c-8a9ecc30954f.png)

**Comment by mazenchami** [comment]
@justinhuskey i'll implement this shortly but do we need to highlight "PT" anywhere on the card? i.e. `5:00 - 5:30 pm PT`

**Comment by justinhuskey** [comment]
@mazenchami 

I'd display times as "12:30pm PT"
