### ISSUE TITLE
Workshops Disclaimer

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#138]
We added a disclaimer over the schedule for the workshop day.  Please add a warning/disclaimer above the workshops in the schedule that you must have a workshop ticket to attend that day.

![image](https://user-images.githubusercontent.com/997157/232871648-25681c4e-e741-467e-ae17-90f7456b2605.png)

**Comment by justinhuskey** [comment]
That works for me @mazenchami
