### ISSUE TITLE
Day 2 after lunch - TALK ( Should be "Trivia Game")

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#140]
I will be giving you a description soon.

It should say "Trivia Game"

Also, add these 3 headshots and socials:
**Jack Herrington**
YouTube: https://www.youtube.com/@jherr
Twitter: https://twitter.com/jherr
![image](https://user-images.githubusercontent.com/997157/232883932-c7b441c6-57ec-4cb9-9c0d-1bab2a3f580a.png)

**Robin Heinze**
Twitter: https://twitter.com/robin_heinze
![image](https://user-images.githubusercontent.com/997157/232883312-8986a41a-8ca2-40fa-86b3-75e9ee1d50a3.png)

**Mike Hartington**
Twitter: https://twitter.com/mhartington
![image](https://user-images.githubusercontent.com/997157/232883612-5ce1a343-4675-438c-94ac-85ab2c7353f5.png)

**Comment by GantMan** [comment]
Currently it's just blank like this:  
![image](https://user-images.githubusercontent.com/997157/232884250-df4f1630-183c-464e-944e-ab1e078a42c2.png)

**Comment by GantMan** [comment]
Higher quality image of Jack
![image](https://user-images.githubusercontent.com/997157/232884588-ab5eff7e-f346-4665-9cd8-b0c022b3b033.png)

**Comment by mazenchami** [comment]
@justinhuskey once you upload these images, please let me know so i can make sure the app consumes them the right way

**Comment by justinhuskey** [comment]
These are uploaded @mazenchami

**Comment by mazenchami** [comment]
@justinhuskey thank you!
@GantMan justin and i discussed this wouldn't be clickable. i assume since you want the socials and all it should be clickable, is that correct?

**Comment by GantMan** [comment]
Yeah, clickable socials plz.

**Comment by mazenchami** [comment]
got it gant! #141 has a comment that this page should mimic the workshop layout for multiple "speakers"
