### ISSUE TITLE
Add secondary speakers

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#141]
Talks that have multiple speakers should have the additional speakers.

e.g. The AWS talk has 2 speakers, and only shows one of them in drilldown.
![image](https://user-images.githubusercontent.com/997157/232884431-09055c56-0a96-447b-b03f-bd165214f24d.png)

**Comment by mazenchami** [comment]
after speaking with justin, we'll go with the following setup:

for single speaker: keep current layout
for multiple speakers: mimic workshop layout
