### ISSUE TITLE
Schedule pulldown gesture not completing automatically each time app is started

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ChainReactApp2023#146]
Steps to reproduce:

- Upon opening the app and tapping "See the schedule", "Wed" is selected and no spinner appears
- Pulldown on the schedule to refresh and the spinner begins animating
- The schedule doesn't snap back up after the pulldown gesture is completed
- The spinner never stops animating
- Switch to other days in the bottom tab and repeat these steps. The same issue occurs.
- Select the Venues tab to load that screen
- Tap the Schedule tab to reload the schedule screen
- Now the pulldown works correctly and snaps back up as expected when the gesture is completed.
- Close the app completely via swipe up
- Restart the app
- The same issue occurs as described above.

iPhone 13 Pro Max
iOS 16.4.1

**Comment by mazenchami** [comment]
@derekgreenberg thanks for logging this error. @morganick resolved this issue this morning and a new build will be out tomorrow morning with a bunch of updates. i'll keep this open for now
