### ISSUE TITLE
general Image/Slider Alignment relative to surrounding content

### ISSUE THREAD

**Issue by yulolimum** [infinitered/ChainReactApp2023#147]
I don't know what the designs look like so feel free to close this issue. 

Slider images have a gutter and thus add extra initial/end slide padding.

| ![telegram-cloud-photo-size-1-5044150914482547440-y](https://user-images.githubusercontent.com/1775841/233171799-c6e3568d-9298-4529-8e68-ce881bbb6d47.jpg) | ![telegram-cloud-photo-size-1-5044150914482547438-y](https://user-images.githubusercontent.com/1775841/233172070-2ab9488f-43c5-4d51-87af-8e0c9cb734a5.jpg) | ![telegram-cloud-photo-size-1-5044150914482547437-y](https://user-images.githubusercontent.com/1775841/233172141-05f04f87-246b-44c6-a7e5-d0414637322f.jpg) |
|------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|

Then there's this:

| ![telegram-cloud-photo-size-1-5044150914482547439-y](https://user-images.githubusercontent.com/1775841/233172355-2d32ff59-cd8a-4601-9d55-83c27235eae1.jpg) |   |   |
|------------------------------------------------------------------------------------------------------------------------------------------------------------|---|---|

**Comment by morganick** [comment]
I believe this is because of the following calculation for spacer width:
https://github.com/infinitered/ChainReactApp2023/blob/main/app/components/carousel/constants.ts#L7

The surrounding text is using 24px of horizontal spacing whereas the above code is going to be variable based on device width.

**Comment by mazenchami** [comment]
Please keep issue #87 in mind while making this fix
