### ISSUE TITLE
CMS suggestion: Lunch Break copy

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ChainReactApp2023#148]
I suggest changing this copy used for lunch breaks
"Both vegetarian and vegan options will be available for anyone with dietary restrictions."

To this:
"Vegetarian, vegan, and gluten-free options will be available."

Why? 
1. There's no need to explain that these options are for anyone with dietary restrictions. Also, there are other dietary restrictions not covered by our catering plan, including kosher, shellfish, dairy, nut, and more.
2. Yes, we will have gluten-free options! That will be welcome news to many attendees.

**Comment by mazenchami** [comment]
cc: @justinhuskey

**Comment by justinhuskey** [comment]
That sounds great! Let's do it

**Comment by justinhuskey** [comment]
This should be updated in the CMS

**Comment by mazenchami** [comment]
I can confirm this update is showing up on the website and app. Thank you @justinhuskey and @derekgreenberg. Closing this out now
