### ISSUE TITLE
[AI] Address should be known

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#160]
![IMG_0344](https://user-images.githubusercontent.com/997157/233729426-206a4c63-0ac4-4435-9c6d-8b44f08ac407.png)

**Comment by mazenchami** [comment]
backend updated:

<img src="https://user-images.githubusercontent.com/9324607/234945837-803ab218-7f6b-4291-b828-b6f065b7c6ec.png" width="300" />
