### ISSUE TITLE
[AI] Tab - Keyboard coveres bottom nav

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#162]
When you're looking at the keyboard, you can't see how to leave.  You have to dismiss keyboard to get back to tabs.  See video:

https://user-images.githubusercontent.com/997157/233732911-60a73c9b-4f76-4108-a049-1a87f56a50aa.MP4

Add button that says "Done" at top left, to return to previous tab.  So it's 1 click instead of 2 odd clicks to leave.

**Comment by justinhuskey** [comment]
There is a weird issue going on where it's difficult to return to the primary navigation... which is a no-no. Once I start interacting with the bot, it's tough to get out of it.

Most chat apps will solve this by having the user click a back button that takes them to the list of conversations they're having. We don't really have that pattern here. 

I expected "clear" to return me to the default state of keyboard closed, chat wiped. Maybe we do that?

**Comment by justinhuskey** [comment]
Also... on iMessages, a swipe down hides the keyboard. We could just add that gesture.

**Comment by justinhuskey** [comment]
@mazenchami Let's do a swipe away gesture on this one, please.
