### ISSUE TITLE
[AI] Chat Icon

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#177]
Why is it a bug?  Can we make it NOT a bug?

**Comment by mazenchami** [comment]
@JenFucci do you have an icon for us for the tabs?

**Comment by JenFucci** [comment]
@mazenchami attached svg & png files for one

[chat-icons.zip](https://github.com/infinitered/ChainReactApp2023/files/11346094/chat-icons.zip)
