### ISSUE TITLE
GitHub links on talk summary pages do not navigate

### ISSUE THREAD

**Issue by joshuayoes** [infinitered/ChainReactApp2023#208]
See Android 4.0.1 via Play Store:

https://user-images.githubusercontent.com/37849890/236345602-0b0e1691-0269-49da-b00c-0f68114cfe1c.mp4

**Comment by joshuayoes** [comment]
https://user-images.githubusercontent.com/37849890/236346067-0bc0ac83-bde3-43cd-acae-f62cfdde32a1.mp4

**Comment by mazenchami** [comment]
@joshuayoes can you confirm if you have the Twitter or GitHub apps installed on this device?

**Comment by joshuayoes** [comment]
Yes I have both

**Comment by joshuayoes** [comment]
I have had some issues in the past with opening GitHub links when the github app was installed as well in other situations

**Comment by joshuayoes** [comment]
Tried the changes from this PR on my device: https://github.com/infinitered/ChainReactApp2023/pull/214

If I try to open the GitHub link with the GitHub app on my phone, it does open GitHub, but it creates some sort of impossible state on my phone.

https://user-images.githubusercontent.com/37849890/236640724-d4cc29ba-7f7c-4cbf-a373-84fed4a1c757.mp4

If I disable opening GitHub links with the mobile app, then it works correctly on a browser.

https://user-images.githubusercontent.com/37849890/236640750-f378692c-f4c9-46fc-9b1d-b4d005f8eb37.mp4

**Comment by joshuayoes** [comment]
I am able to open GitHub profile on other apps on this device

https://user-images.githubusercontent.com/37849890/236640778-95529515-2b0e-4e6a-8c77-f1e1da4b2a8d.mp4

**Comment by joshuayoes** [comment]
I tested this on the latest build with the PR changes and it works!
