### ISSUE TITLE
Refreshing schedule does not refetch data

### ISSUE THREAD

**Issue by joshuayoes** [infinitered/ChainReactApp2023#209]
Not sure if this should be the case, but as a user, I would expect the data to be refetched, or have an indicator that something was refetched when swiping and receiving the spinning wheel 

https://user-images.githubusercontent.com/37849890/236347108-5e9eee5b-7c0a-4989-ba11-81285ed92650.mp4

**Comment by morganick** [comment]
Hey @joshuayoes, that spinner that pulls down is the `RefreshControl` coming in to let you know we're refreshing the data in the background: https://github.com/infinitered/ChainReactApp2023/blob/main/app/screens/ScheduleScreen/ScheduleScreen.tsx#L242

This is different that the initial loading state that you see when the app loads for the first time. It won't go back into that initial loading state when we are refetching. It is going to display the data from cache and then behind the scenes revalidate; stale-while-revalidating. It will only update the data if it has changed.

Let me know if I missed something.

**Comment by joshuayoes** [comment]
That makes sense. This was an observation from a UX perspective without that knowledge, but if that is the case, then this isn't an issue. It may be nice to have some sort of tint or something in the UI to indicate that the refetch is pending, but that's not a huge priority imo
