### ISSUE TITLE
Layout jumps on Android on screen first load

### ISSUE THREAD

**Issue by joshuayoes** [infinitered/ChainReactApp2023#210]
When a screen first loads, the header appears to jump down and then up to its expected layout. 

https://user-images.githubusercontent.com/37849890/236347723-7d30150a-e7db-4b9f-bee6-a388f2831f1f.mp4

However, this does not happen once a screen is already mounted and then is remounted.

https://user-images.githubusercontent.com/37849890/236347822-0c918dd5-f296-4225-8ef4-b7b437c23581.mp4

**Comment by morganick** [comment]
Replicated: Only happens on initial screen load. 🤔

**Comment by joshuayoes** [comment]
Verified the changes on my device with a build from the PR, this looks good!
