### ISSUE TITLE
CMS Change to schedule content

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ChainReactApp2023#218]
For web and mobile apps, please change this description of the morning break for 5/18 and 5/19 from this:
"Take a break to stretch your legs or grab a coffee or a snack. Talks resume in 30 mins if you plan to leave the venue!"
to this:

"Take a break to stretch your legs or grab a cup of coffee, tea, or water. Talks resume in 30 mins if you plan to leave the venue!"

There is no 'snack' service between breakfast and lunch at the conference and I don't want the schedule to give people the wrong impression.

**Comment by mazenchami** [comment]
CMS has been updated!
