### ISSUE TITLE
Accessibility of social icons in speaker cards

### ISSUE THREAD

**Issue by chrisdemars** [infinitered/ChainReactApp2023#227]
When using a screen reader, it skips over the social media icon entirely.By adding an `aria-label={url}` to the `<Pressable />` component, it will fix that issue by announcing the url of the social media destination to the user.

**Comment by mazenchami** [comment]
after discussing with Chris, we'll add the following props to the `/app/components/SocialButton.tsx > Pressable`: 
```
accessibilityRole="button"
accessibilityLabel={icon}
accessibilityHint="Navigates to `${icon}`"
```
