### ISSUE TITLE
Not sure if on purpose or not... but plz no

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#82]
HEAVY pixelation on the the footer

![image](https://user-images.githubusercontent.com/997157/229552606-0068db95-9d06-476b-b690-a3504e78c968.png)

Pixelation means either OLD or MISTAKE.  Two things we do not want on our app brand.

**Comment by JenFucci** [comment]
[icons.zip](https://github.com/infinitered/ChainReactApp2023/files/11151843/icons.zip)

**Comment by mazenchami** [comment]
updated icons—[icons.zip](https://github.com/infinitered/ChainReactApp2023/files/11160686/icons.zip)

**Comment by mazenchami** [comment]
This issue has been resolved, thank you all!
