### ISSUE TITLE
Constant Welcomes

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#83]
every time I close and open the app, I see the welcome message.   Can we skip that if it hasn't changed and go straight to schedule?

**Comment by mazenchami** [comment]
Notes: this might be `ErrorBoundry` triggering an error: will need to ping crashlytics from boundary also

**Comment by ecroce** [comment]
Came here to report the same. This is only on like a complete close for me (swipe the app away on iOS) but is frustrating

**Comment by mazenchami** [comment]
Thank you @ecroce, yes i agree with you its frustrating. @jonmajorc let me know if you have the bandwidth to look into this and if not let us know so @morganick can raise it up in priority pleae.

**Comment by morganick** [comment]
@ecroce & @GantMan let me know if you have any further issues with this.
