### ISSUE TITLE
Pull to Refresh?

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#84]
Does the app schedule do pull to refresh?  I don't seem to see any indicator.

IF not... how could I update the schedule?

**Comment by mazenchami** [comment]
@JenFucci would the pure native pull to refresh with their refresh indicators be enough for this?

| iOS                                     | Android                                     |
| --------------------------------------- | ------------------------------------------- |
| <img src="https://user-images.githubusercontent.com/9324607/229840489-f8c539ea-ecf6-4f7c-87af-cfe5b648aa9b.gif" width="250" /> | <img src="https://user-images.githubusercontent.com/9324607/229840485-affe1e74-86ab-441a-98f9-6232535a9df1.gif" width="250" /> |

**Comment by JenFucci** [comment]
@mazenchami yep! That works

**Comment by mazenchami** [comment]
This issue has been resolved, thank you all!
