### ISSUE TITLE
Venue OVERLOAD with Sponsors

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#86]
Why are the sponsors listed in the Venue tab?

Probably should have subsections in Info.  Info needs organization.

**Comment by mazenchami** [comment]
@JenFucci @justinhuskey thoughts on this ticket?

**Comment by justinhuskey** [comment]
Agree with Gant on it.

**Comment by mazenchami** [comment]
This issue has been resolved and merged to `main`.
