### ISSUE TITLE
Multi-scroll Width Issue - Multi Speakers

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2023#87]
When you go to panelists - it looks like that's it.  1 person.  You have to stare for a while before you notice the small bar on the right, and realize you should swipe.

![image](https://user-images.githubusercontent.com/997157/229556474-131f716e-7254-48b6-aa3d-c823d9e6a6e9.png)

Second photo should be more prominent to make swipe obvious.

**Comment by mazenchami** [comment]
@GantMan i can't seem to find this page. can you please point me to it?

**Comment by GantMan** [comment]
This is the speakers drill-down list of any panel discussion (multi speaker talks)

**Comment by mazenchami** [comment]
This issue has been resolved, thank you all!
