### ISSUE TITLE
"Open Our Yelp Guide" Kills the App

### ISSUE THREAD

**Issue by justinhuskey** [infinitered/ChainReactApp2023#89]
Whenever I tap on "Open Our Yelp Guide" on the **Explore** tab, it kills the app.

**Comment by mazenchami** [comment]
@justinhuskey thanks for logging this. I see a note in the code that its crashing due to it not coming back from the CMS. @JenFucci, this is a link we would need setup

**Comment by mazenchami** [comment]
for now, will default to: `https://www.yelp.com/`
