### ISSUE TITLE
Info -- IR team doesn't have a description

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ChainReactApp2023#91]
On the *Info* Tab, it says "Hosted by the Infinite Red team" and a photo of us, but there's no info on who we are, what we do, anything. We could be a conf organizing team for all it says there. So I'd like an IR blurb there.

![image](https://user-images.githubusercontent.com/1479215/230125737-3583c4f5-a033-4682-bab9-4a93ae4ea7b3.png)

**Comment by mazenchami** [comment]
@justinhuskey similar to the other issue, the `Hosted by the Infinite Red team` section is all static data

**Comment by justinhuskey** [comment]
Hey @mazenchami and @jamonholmgren 👋 

Tried writing something up. What do you all think about this? 

> Headline: Chain React – Hosted by Infinite Red
> 
> Since 2017, people have attended Chain React to learn from the biggest names and companies in React Native. 
> 
> Chain React is hosted by the team at Infinite Red. 
> 
> React Native is central to everything Infinite Red creates, shares, and contributes to the community. As one of the most popular React Native consultancies, their team helps companies like GasBuddy, Zoom, and Microsoft on their most important projects.
> 
> Infinite Red also hosts the React Native Radio podcast, maintains Ignite (the most popular boilerplate for Expo and React Native), and writes the React Native Newsletter. 
> 
> Link (to infinite.red): More about Infinite Red
