### ISSUE TITLE
Welcome -- doesn't say what Chain React is

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ChainReactApp2023#92]
On the Welcome screen, it doesn't say what Chain React is. Probably should say something about "the biggest and best React Native conference in the USA" or something.

![image](https://user-images.githubusercontent.com/1479215/230126060-1a3a06f9-86af-4215-91fa-3cb7f59e5e4d.png)

**Comment by mazenchami** [comment]
@justinhuskey i noticed this is static and not pulling from the CMS. Let me know if you'd prefer it pull from the CMS. If not, can you provide me with the updated text please?

**Comment by justinhuskey** [comment]
@mazenchami I have this one over on https://github.com/infinitered/ChainReactApp2023/issues/110

I mention that it's the 4th annual React Native conference, but I also used it primarily as introduction to the app. I want them to know it has schedules, info, and a city guide. 

We can switch it to marketing speak that's more CR general post-event.

**Comment by mazenchami** [comment]
awesome, will close this issue then and have that house the information.
