### ISSUE TITLE
The last item in carousel has additional padding

### ISSUE THREAD

**Issue by jonmajorc** [infinitered/ChainReactApp2023#96]
https://user-images.githubusercontent.com/7799266/230182686-f6991bf8-6925-48f2-9411-6f2b8d07e294.mov

![CleanShot 2023-04-05 at 14 20 49](https://user-images.githubusercontent.com/7799266/230183281-062ea23e-842d-4794-81d8-e130d46c6a1b.png)

**Comment by mazenchami** [comment]
@jonmajorc this was fixed in a recent build: #94
