### ISSUE TITLE
I can't select text on my iPhone (Improvement???)

### ISSUE THREAD

**Issue by jonmajorc** [infinitered/ChainReactApp2023#99]
I noticed I cannot select any text within the app. From time to time, I find myself selecting text to copy and paste into my "app of choice." The best and most frequent example is copying text to paste into Google Maps. From my knowledge, still today, you cannot make Google Maps the Default map app (booooooo... although Apple Maps is getting a lot better 😅 🤷‍♂️ )

**Comment by mazenchami** [comment]
Thank you for reporting this issue @jonmajorc. This issue has been resolved and merged to `main`. You can now "select" the addresses of all the `Venues`.
